export const LOCATIONS = [
  { id: "bai-rang", name: "Bãi Rạng, Núi Thành", country: "Vietnam", lat: 15.4833, lon: 108.7167, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "da-nang", name: "Đà Nẵng (Mỹ Khê)", country: "Vietnam", lat: 16.0544, lon: 108.2022, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "hoi-an", name: "Cửa Đại, Hội An", country: "Vietnam", lat: 15.8801, lon: 108.3380, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "nha-trang", name: "Nha Trang", country: "Vietnam", lat: 12.2388, lon: 109.1967, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "mui-ne", name: "Mũi Né, Phan Thiết", country: "Vietnam", lat: 10.9333, lon: 108.2833, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "vung-tau", name: "Vũng Tàu", country: "Vietnam", lat: 10.4113, lon: 107.1362, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "phu-quoc", name: "Phú Quốc", country: "Vietnam", lat: 10.2899, lon: 103.9840, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "con-dao", name: "Côn Đảo", country: "Vietnam", lat: 8.6833, lon: 106.6167, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "ha-long", name: "Hạ Long, Quảng Ninh", country: "Vietnam", lat: 20.9101, lon: 107.1839, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "sam-son", name: "Sầm Sơn, Thanh Hóa", country: "Vietnam", lat: 19.7306, lon: 105.9028, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "lang-co", name: "Lăng Cô, Huế", country: "Vietnam", lat: 16.2186, lon: 108.0739, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "quy-nhon", name: "Quy Nhơn", country: "Vietnam", lat: 13.7829, lon: 109.2196, timeZone: "Asia/Ho_Chi_Minh" },
  { id: "bay-of-fundy", name: "Bay of Fundy", country: "Canada", lat: 45.2600, lon: -64.1600, timeZone: "America/Halifax" },
  { id: "mont-saint-michel", name: "Mont-Saint-Michel", country: "France", lat: 48.6360, lon: -1.5115, timeZone: "Europe/Paris" },
  { id: "london-thames", name: "London (River Thames)", country: "United Kingdom", lat: 51.5074, lon: -0.1278, timeZone: "Europe/London" },
  { id: "venice", name: "Venice", country: "Italy", lat: 45.4408, lon: 12.3155, timeZone: "Europe/Rome" },
  { id: "new-york-harbor", name: "New York Harbor", country: "United States", lat: 40.7000, lon: -74.0100, timeZone: "America/New_York" },
  { id: "san-francisco-bay", name: "San Francisco Bay", country: "United States", lat: 37.8060, lon: -122.4650, timeZone: "America/Los_Angeles" },
  { id: "rio-de-janeiro", name: "Rio de Janeiro", country: "Brazil", lat: -22.9068, lon: -43.1729, timeZone: "America/Sao_Paulo" },
  { id: "cape-town", name: "Cape Town", country: "South Africa", lat: -33.9249, lon: 18.4241, timeZone: "Africa/Johannesburg" },
  { id: "sydney-harbour", name: "Sydney Harbour", country: "Australia", lat: -33.8568, lon: 151.2153, timeZone: "Australia/Sydney" },
  { id: "tokyo-bay", name: "Tokyo Bay", country: "Japan", lat: 35.4437, lon: 139.6380, timeZone: "Asia/Tokyo" },
  { id: "singapore-strait", name: "Singapore Strait", country: "Singapore", lat: 1.2200, lon: 103.8500, timeZone: "Asia/Singapore" },
  { id: "auckland", name: "Auckland", country: "New Zealand", lat: -36.8509, lon: 174.7645, timeZone: "Pacific/Auckland" },
]
